# Generated by Django 5.2.10 on 2026-04-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_copra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doedieselprice',
            name='period_label',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doedieselupload',
            name='period_label',
            field=models.DateField(blank=True, help_text='Start date of the period, e.g. 2026-04-21', null=True),
        ),
    ]
