# Generated by Django 5.2.10 on 2026-01-25 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_copra', '0002_excelupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastlog',
            name='farmer',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'farmer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
