# Generated by Django 5.2.10 on 2026-04-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_copra', '0002_alter_doedieselprice_period_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doedieselprice',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doedieselprice',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doedieselupload',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of the period', null=True),
        ),
        migrations.AddField(
            model_name='doedieselupload',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date of the period', null=True),
        ),
    ]
