# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_copra', '0003_alter_forecastlog_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='p',
            field=models.IntegerField(default=1, help_text='AR order (autoregressive)'),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='d',
            field=models.IntegerField(default=1, help_text='I order (differencing)'),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='q',
            field=models.IntegerField(default=1, help_text='MA order (moving average)'),
        ),
    ]
