# Generated by Django 5.2.10 on 2026-01-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_copra', '0004_trainedmodel_p_d_q'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecastlog',
            old_name='armer_input_peso_dollar_rate',
            new_name='farmer_input_peso_dollar_rate',
        ),
    ]
