# Generated by Django 5.2.10 on 2026-01-26 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_copra', '0005_rename_armer_input_peso_dollar_rate_forecastlog_farmer_input_peso_dollar_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastlog',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
