# Generated by Django 5.2.10 on 2026-02-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_copra', '0006_alter_forecastlog_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('farmer', 'Farmer')], default='admin', max_length=10),
        ),
    ]
