# Generated by Django 5.2.10 on 2026-02-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_copra', '0007_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastlog',
            name='farmer',
        ),
    ]
