# Generated by Django 5.2.10 on 2026-02-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_copra', '0008_remove_forecastlog_farmer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainedmodel',
            options={'ordering': ['-training_date'], 'verbose_name_plural': 'Trained Models'},
        ),
        migrations.RemoveField(
            model_name='trainedmodel',
            name='accuracy',
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='aic',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Akaike Information Criterion', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='mae',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Mean Absolute Error', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='mape',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Mean Absolute Percentage Error (%)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='rmse',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Root Mean Squared Error', max_digits=10, null=True),
        ),
    ]
