# Generated by Django 5.2.10 on 2026-02-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_copra', '0009_alter_trainedmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='forecastlog',
            name='confidence_lower',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='forecastlog',
            name='confidence_upper',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='forecastlog',
            name='model_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='forecastlog',
            name='price_avg',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='forecastlog',
            name='price_max',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='forecastlog',
            name='price_min',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='forecastlog',
            name='trend',
            field=models.CharField(blank=True, default='stable', max_length=50),
        ),
        migrations.AddField(
            model_name='forecastlog',
            name='volatility',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forecastlog',
            name='farmer_input_oil_price_trend',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='forecastlog',
            name='farmer_input_peso_dollar_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='forecastlog',
            name='forecast_horizon',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='forecastlog',
            name='price_predicted',
            field=models.FloatField(),
        ),
    ]
