# Generated by Django 5.2.10 on 2026-02-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_copra', '0010_alter_forecastlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastlog',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Forecast Logs'},
        ),
        migrations.RemoveField(
            model_name='forecastlog',
            name='confidence_lower',
        ),
        migrations.RemoveField(
            model_name='forecastlog',
            name='confidence_upper',
        ),
        migrations.RemoveField(
            model_name='forecastlog',
            name='model_used',
        ),
        migrations.RemoveField(
            model_name='forecastlog',
            name='price_avg',
        ),
        migrations.RemoveField(
            model_name='forecastlog',
            name='price_max',
        ),
        migrations.RemoveField(
            model_name='forecastlog',
            name='price_min',
        ),
        migrations.RemoveField(
            model_name='forecastlog',
            name='trend',
        ),
        migrations.RemoveField(
            model_name='forecastlog',
            name='volatility',
        ),
        migrations.AlterField(
            model_name='forecastlog',
            name='farmer_input_oil_price_trend',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='forecastlog',
            name='farmer_input_peso_dollar_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='forecastlog',
            name='forecast_horizon',
            field=models.IntegerField(help_text='Number of days to forecast'),
        ),
        migrations.AlterField(
            model_name='forecastlog',
            name='price_predicted',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
