# Generated by Django 5.2.10 on 2026-02-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_copra', '0011_alter_forecastlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastlog',
            name='farmer_input_peso_dollar_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
