# Generated by Django 5.2.10 on 2026-02-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_copra', '0012_alter_forecastlog_farmer_input_peso_dollar_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastlog',
            name='farmer_input_peso_dollar_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
