# Generated by Django 5.2.10 on 2026-03-10 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_copra', '0013_alter_forecastlog_farmer_input_peso_dollar_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastlog',
            name='model_used',
            field=models.ForeignKey(blank=True, help_text='The ARIMAX model that produced this forecast', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_logs', to='forecast_copra.trainedmodel'),
        ),
    ]
