# Generated by Django 5.2.10 on 2026-03-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_copra', '0014_forecastlog_model_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='plot_actual',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='plot_preds',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
