# Generated by Django 5.2.10 on 2026-04-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_copra', '0015_trainedmodel_plot_actual_trainedmodel_plot_preds'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastlog',
            name='farmer_input_diesel_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='forecastlog',
            name='farmer_input_labor_min_wage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='diesel_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Diesel price per liter', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='labor_min_wage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum labor wage', max_digits=10, null=True),
        ),
    ]
